from __future__ import annotations

import json
import zipfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from backup_engine.backup.service import run_backup
from backup_engine.clock import FixedClock
from backup_engine.restore.service import run_restore


@dataclass(frozen=True)
class _FileSpec:
    relative_path: Path
    content: bytes


def _write_source_tree(root: Path, files: list[_FileSpec]) -> None:
    for spec in files:
        full_path = root / spec.relative_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_bytes(spec.content)


def _find_single_backup_manifest(search_root: Path) -> Path:
    """
    Locate the single backup manifest generated by an end-to-end run.

    We intentionally avoid assuming a specific internal manifest layout under data_root.
    If multiple candidates exist, we fail with a helpful message so the layout can be
    made explicit later (or the selector can be tightened).
    """
    candidates = sorted(
        manifest_path
        for pattern in ("manifest.json", "*.manifest.json")
        for manifest_path in search_root.rglob(pattern)
        if manifest_path.is_file()
    )

    if len(candidates) == 1:
        return candidates[0]

    tree_listing = "\n".join(
        str(p.relative_to(search_root)) for p in sorted(search_root.rglob("*"))
    )
    raise AssertionError(
        "Expected exactly one 'manifest.json' under data_root.\n"
        f"Found {len(candidates)} candidates:\n"
        + "\n".join(f"  - {p}" for p in candidates)
        + "\n\n"
        f"search_root contents:\n{tree_listing}"
    )


def _find_single_backup_archive(search_root: Path) -> Path:
    """
    Locate the single backup archive generated by an end-to-end compressed run.

    We intentionally avoid assuming a specific internal layout under data_root.
    """
    candidates = sorted(p for p in search_root.rglob("*.zip"))

    if len(candidates) == 1:
        return candidates[0]

    tree_listing = "\n".join(
        str(p.relative_to(search_root)) for p in sorted(search_root.rglob("*"))
    )
    raise AssertionError(
        "Expected exactly one '*.zip' or '*.tar.zst' under data_root.\n"
        f"Found {len(candidates)} candidates:\n"
        + "\n".join(f"  - {p}" for p in candidates)
        + "\n\n"
        f"search_root contents:\n{tree_listing}"
    )


def _assert_tree_matches(source_root: Path, restored_root: Path, files: list[_FileSpec]) -> None:
    for spec in files:
        src_path = source_root / spec.relative_path
        dst_path = restored_root / spec.relative_path

        assert src_path.exists(), f"Missing expected source file: {src_path}"
        assert dst_path.exists(), f"Missing restored file: {dst_path}"

        assert dst_path.read_bytes() == src_path.read_bytes(), (
            f"Content mismatch: {spec.relative_path}"
        )
        assert dst_path.stat().st_size == src_path.stat().st_size, (
            f"Size mismatch: {spec.relative_path}"
        )


def test_end_to_end_backup_then_restore_verify_size_and_artifacts_survive(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    data_root = tmp_path / "data_root"
    restore_destination = tmp_path / "restore_destination"

    files = [
        _FileSpec(relative_path=Path("alpha.txt"), content=b"alpha\n"),
        _FileSpec(relative_path=Path("nested") / "beta.bin", content=b"\x00\x01\x02\x03"),
        _FileSpec(relative_path=Path("nested") / "deeper" / "gamma.txt", content=b"gamma\n"),
    ]

    _write_source_tree(source_root, files)

    # Backup (plan + execute) into an isolated data_root.
    run_backup(
        profile_name="end_to_end",
        source=source_root,
        dry_run=False,
        data_root=data_root,
        excluded_directory_names=None,
        excluded_file_names=None,
        use_default_excludes=True,
        max_items=100,
        write_plan=False,
        plan_path=None,
        overwrite_plan=False,
        clock=None,
        execute=True,
        force=True,
        break_lock=True,
    )

    manifest_path = _find_single_backup_manifest(data_root)

    # Restore into a clean destination root.
    run_restore(
        manifest_path=manifest_path,
        destination_root=restore_destination,
        mode="overwrite",
        verify="size",
        dry_run=False,
        data_root=data_root,
        clock=None,
    )

    # Validate restored files.
    _assert_tree_matches(source_root, restore_destination, files)

    # Artifacts must survive promotion and land in the final destination root.
    artifacts_root = restore_destination / ".wcbt_restore"
    assert artifacts_root.exists(), "Expected restore artifacts root to exist after promotion."
    assert artifacts_root.is_dir(), (
        "Expected restore artifacts root to be a directory after promotion."
    )


def test_end_to_end_backup_compress_zip_then_restore_from_archive(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    data_root = tmp_path / "data_root"
    restore_destination = tmp_path / "restore_destination"

    files = [
        _FileSpec(relative_path=Path("alpha.txt"), content=b"alpha\n"),
        _FileSpec(relative_path=Path("nested") / "beta.bin", content=b"\x00\x01\x02\x03"),
        _FileSpec(relative_path=Path("nested") / "deeper" / "gamma.txt", content=b"gamma\n"),
    ]

    _write_source_tree(source_root, files)

    # Backup (execute + compress). We use zip for deterministic tests without optional deps.
    clock = FixedClock(datetime.fromisoformat("2026-01-02T03:04:05+00:00"))

    run_backup(
        profile_name="end_to_end",
        source=source_root,
        dry_run=False,
        data_root=data_root,
        excluded_directory_names=None,
        excluded_file_names=None,
        use_default_excludes=True,
        max_items=100,
        write_plan=False,
        plan_path=None,
        overwrite_plan=False,
        clock=clock,
        execute=True,
        force=True,
        break_lock=True,
        compress=True,
        compression="zip",
        job_name="photos",
    )

    archive_path = _find_single_backup_archive(source_root.parent / "OZ0")
    assert archive_path.exists()
    assert archive_path.parent.name == "OZ0"
    assert archive_path.parent == source_root.parent / "OZ0"
    assert archive_path.name == "photos.20260102_030405Z.OZ0.zip"

    manifest_path = _find_single_backup_manifest(source_root.parent / "OZ0")
    assert manifest_path.parent == archive_path.parent
    assert manifest_path.name == "photos.20260102_030405Z.manifest.json"

    # Restore accepts a manifest.json path; when manifest includes archive metadata,
    # restore stages from that derived archive.
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert "archive" in payload, (
        "Expected run manifest to include archive metadata after compression."
    )
    assert Path(payload["archive_root"]) == source_root.parent / "OZ0"
    assert payload["archive"]["relative_path"] == archive_path.name
    assert all("destination_path" not in operation for operation in payload["operations"])
    execution = payload.get("execution", {})
    results = execution.get("results", []) if isinstance(execution, dict) else []
    assert all("destination_path" not in result for result in results)

    with zipfile.ZipFile(archive_path, "r") as archive_file:
        archive_names = archive_file.namelist()
    assert all(not name.endswith("manifest.json") for name in archive_names)
    assert all("plan.txt" not in name for name in archive_names)

    run_restore(
        manifest_path=manifest_path,
        destination_root=restore_destination,
        mode="overwrite",
        verify="size",
        dry_run=False,
        data_root=data_root,
        clock=None,
    )

    _assert_tree_matches(source_root, restore_destination, files)

    artifacts_root = restore_destination / ".wcbt_restore"
    assert artifacts_root.exists(), "Expected restore artifacts root to exist after promotion."
    assert artifacts_root.is_dir(), (
        "Expected restore artifacts root to be a directory after promotion."
    )
    staging_root = data_root / "profiles" / "end_to_end" / "work" / "oz0_staging"
    assert (not staging_root.exists()) or (not any(staging_root.iterdir()))


def test_end_to_end_backup_compress_derives_oz0_root_from_source_parent(tmp_path: Path) -> None:
    source_root = tmp_path / "testing"
    data_root = tmp_path / "data_root"
    _write_source_tree(
        source_root,
        [_FileSpec(relative_path=Path("world.dat"), content=b"data")],
    )

    clock = FixedClock(datetime.fromisoformat("2026-04-16T16:39:55+00:00"))

    result = run_backup(
        profile_name="end_to_end",
        source=source_root,
        dry_run=False,
        data_root=data_root,
        excluded_directory_names=None,
        excluded_file_names=None,
        use_default_excludes=True,
        max_items=100,
        write_plan=False,
        plan_path=None,
        overwrite_plan=False,
        clock=clock,
        execute=True,
        force=True,
        break_lock=True,
        compress=True,
        compression="zip",
        job_name="Minecraft",
    )

    expected_oz0_root = tmp_path / "OZ0"
    expected_archive = expected_oz0_root / "Minecraft.20260416_163955Z.OZ0.zip"
    expected_manifest = expected_oz0_root / "Minecraft.20260416_163955Z.manifest.json"

    assert result.archive_root == expected_oz0_root
    assert expected_archive.is_file()
    assert expected_manifest.is_file()

    payload = json.loads(expected_manifest.read_text(encoding="utf-8"))
    assert Path(payload["archive_root"]) == expected_oz0_root
    assert payload["archive"]["relative_path"] == expected_archive.name


def test_backup_manifest_persists_gui_job_identity(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    data_root = tmp_path / "data_root"

    files = [
        _FileSpec(relative_path=Path("alpha.txt"), content=b"alpha\n"),
    ]

    _write_source_tree(source_root, files)

    run_backup(
        profile_name="end_to_end",
        source=source_root,
        dry_run=False,
        data_root=data_root,
        excluded_directory_names=None,
        excluded_file_names=None,
        use_default_excludes=True,
        max_items=100,
        write_plan=False,
        plan_path=None,
        overwrite_plan=False,
        clock=None,
        execute=True,
        force=True,
        break_lock=True,
        job_id="job-a-id",
        job_name="Job A",
    )

    manifest_path = _find_single_backup_manifest(data_root)
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))

    assert payload["job_id"] == "job-a-id"
    assert payload["job_name"] == "Job A"
