from __future__ import annotations

import json
import shutil
import zipfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from backup_engine.backup.service import run_backup
from backup_engine.clock import FixedClock
from backup_engine.restore.service import run_restore


def _runtime_artifacts_root(destination_root: Path, run_id: str) -> Path:
    return destination_root.with_name(f"{destination_root.name}.wcbt_restore") / run_id


@dataclass(frozen=True)
class _FileSpec:
    relative_path: Path
    content: bytes


def _write_source_tree(root: Path, files: list[_FileSpec]) -> None:
    for spec in files:
        full_path = root / spec.relative_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_bytes(spec.content)


def _find_single_backup_manifest(search_root: Path) -> Path:
    """
    Locate the single backup manifest generated by an end-to-end run.

    We intentionally avoid assuming a specific internal manifest layout under data_root.
    If multiple candidates exist, we fail with a helpful message so the layout can be
    made explicit later (or the selector can be tightened).
    """
    candidates = sorted(
        manifest_path
        for pattern in ("manifest.json", "*.manifest.json")
        for manifest_path in search_root.rglob(pattern)
        if manifest_path.is_file()
    )

    if len(candidates) == 1:
        return candidates[0]

    tree_listing = "\n".join(
        str(p.relative_to(search_root)) for p in sorted(search_root.rglob("*"))
    )
    raise AssertionError(
        "Expected exactly one 'manifest.json' under data_root.\n"
        f"Found {len(candidates)} candidates:\n"
        + "\n".join(f"  - {p}" for p in candidates)
        + "\n\n"
        f"search_root contents:\n{tree_listing}"
    )


def _find_single_backup_archive(search_root: Path) -> Path:
    """
    Locate the single backup archive generated by an end-to-end compressed run.

    We intentionally avoid assuming a specific internal layout under data_root.
    """
    candidates = sorted(p for p in search_root.rglob("*.zip"))

    if len(candidates) == 1:
        return candidates[0]

    tree_listing = "\n".join(
        str(p.relative_to(search_root)) for p in sorted(search_root.rglob("*"))
    )
    raise AssertionError(
        "Expected exactly one '*.zip' or '*.tar.zst' under data_root.\n"
        f"Found {len(candidates)} candidates:\n"
        + "\n".join(f"  - {p}" for p in candidates)
        + "\n\n"
        f"search_root contents:\n{tree_listing}"
    )


def _assert_tree_matches(source_root: Path, restored_root: Path, files: list[_FileSpec]) -> None:
    for spec in files:
        src_path = source_root / spec.relative_path
        dst_path = restored_root / spec.relative_path

        assert src_path.exists(), f"Missing expected source file: {src_path}"
        assert dst_path.exists(), f"Missing restored file: {dst_path}"

        assert dst_path.read_bytes() == src_path.read_bytes(), (
            f"Content mismatch: {spec.relative_path}"
        )
        assert dst_path.stat().st_size == src_path.stat().st_size, (
            f"Size mismatch: {spec.relative_path}"
        )


def test_end_to_end_backup_then_restore_verify_size_and_artifacts_survive(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    data_root = tmp_path / "data_root"
    restore_destination = tmp_path / "restore_destination"

    files = [
        _FileSpec(relative_path=Path("alpha.txt"), content=b"alpha\n"),
        _FileSpec(relative_path=Path("nested") / "beta.bin", content=b"\x00\x01\x02\x03"),
        _FileSpec(relative_path=Path("nested") / "deeper" / "gamma.txt", content=b"gamma\n"),
    ]

    _write_source_tree(source_root, files)

    # Backup (plan + execute) into an isolated data_root.
    run_backup(
        profile_name="end_to_end",
        source=source_root,
        dry_run=False,
        data_root=data_root,
        excluded_directory_names=None,
        excluded_file_names=None,
        use_default_excludes=True,
        max_items=100,
        write_plan=False,
        plan_path=None,
        overwrite_plan=False,
        clock=None,
        execute=True,
        force=True,
        break_lock=True,
    )

    manifest_path = _find_single_backup_manifest(source_root.parent / "source.OZ0")

    # Restore into a clean destination root.
    run_restore(
        manifest_path=manifest_path,
        destination_root=restore_destination,
        mode="overwrite",
        verify="size",
        dry_run=False,
        data_root=data_root,
        clock=None,
    )

    # Validate restored files.
    _assert_tree_matches(source_root, restore_destination, files)

    artifacts_root = _runtime_artifacts_root(restore_destination, manifest_path.parent.name)
    assert artifacts_root.exists(), "Expected restore artifacts root to exist after promotion."
    assert artifacts_root.is_dir(), "Expected restore artifacts root to be a directory."
    assert not (restore_destination / ".wcbt_restore").exists()


def test_end_to_end_backup_compress_zip_then_restore_from_archive(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    data_root = tmp_path / "data_root"
    restore_destination = tmp_path / "restore_destination"

    files = [
        _FileSpec(relative_path=Path("alpha.txt"), content=b"alpha\n"),
        _FileSpec(relative_path=Path("nested") / "beta.bin", content=b"\x00\x01\x02\x03"),
        _FileSpec(relative_path=Path("nested") / "deeper" / "gamma.txt", content=b"gamma\n"),
    ]

    _write_source_tree(source_root, files)

    # Backup (execute + compress). We use zip for deterministic tests without optional deps.
    clock = FixedClock(datetime.fromisoformat("2026-01-02T03:04:05+00:00"))

    run_backup(
        profile_name="end_to_end",
        source=source_root,
        dry_run=False,
        data_root=data_root,
        excluded_directory_names=None,
        excluded_file_names=None,
        use_default_excludes=True,
        max_items=100,
        write_plan=False,
        plan_path=None,
        overwrite_plan=False,
        clock=clock,
        execute=True,
        force=True,
        break_lock=True,
        compress=True,
        compression="zip",
        job_name="photos",
    )

    archive_path = _find_single_backup_archive(source_root.parent / "source.OZ0")
    assert archive_path.exists()
    assert archive_path.parent.name == "source.OZ0"
    assert archive_path.parent == source_root.parent / "source.OZ0"
    assert archive_path.name == "photos.20260102_030405Z.OZ0.zip"

    manifest_path = _find_single_backup_manifest(source_root.parent / "source.OZ0")
    assert manifest_path.parent == archive_path.parent
    assert manifest_path.name == "photos.20260102_030405Z.manifest.json"

    # Restore accepts a manifest.json path; when manifest includes archive metadata,
    # restore stages from that derived archive.
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert "archive" in payload, (
        "Expected run manifest to include archive metadata after compression."
    )
    assert Path(payload["archive_root"]) == source_root.parent / "source.OZ0"
    assert payload["archive_format"] == "zip"
    assert payload["compression_method"] == "deflate"
    assert payload["compression_level"] is None
    assert payload["archive_writer_version"] is None
    assert payload["archive_extension"] == ".zip"
    assert payload["archive"]["relative_path"] == archive_path.name
    assert all("destination_path" not in operation for operation in payload["operations"])
    execution = payload.get("execution", {})
    results = execution.get("results", []) if isinstance(execution, dict) else []
    assert all("destination_path" not in result for result in results)

    with zipfile.ZipFile(archive_path, "r") as archive_file:
        archive_names = archive_file.namelist()
    assert all(not name.endswith("manifest.json") for name in archive_names)
    assert all("plan.txt" not in name for name in archive_names)

    run_restore(
        manifest_path=manifest_path,
        destination_root=restore_destination,
        mode="overwrite",
        verify="size",
        dry_run=False,
        data_root=data_root,
        clock=None,
    )

    _assert_tree_matches(source_root, restore_destination, files)

    artifacts_root = _runtime_artifacts_root(restore_destination, "20260102_030405Z")
    assert artifacts_root.exists(), "Expected restore artifacts root to exist after promotion."
    assert artifacts_root.is_dir(), "Expected restore artifacts root to be a directory."
    assert not (restore_destination / ".wcbt_restore").exists()
    assert not restore_destination.with_name(
        f"{restore_destination.name}.wcbt_restore_extract"
    ).exists()
    assert not restore_destination.with_name(f"{restore_destination.name}.wcbt_stage").exists()
    staging_root = data_root / "profiles" / "end_to_end" / "work" / "oz0_staging"
    assert (not staging_root.exists()) or (not any(staging_root.iterdir()))


def test_end_to_end_backup_compress_derives_oz0_root_from_source_parent(tmp_path: Path) -> None:
    source_root = tmp_path / "testing"
    data_root = tmp_path / "data_root"
    _write_source_tree(
        source_root,
        [_FileSpec(relative_path=Path("world.dat"), content=b"data")],
    )

    clock = FixedClock(datetime.fromisoformat("2026-04-16T16:39:55+00:00"))

    result = run_backup(
        profile_name="end_to_end",
        source=source_root,
        dry_run=False,
        data_root=data_root,
        excluded_directory_names=None,
        excluded_file_names=None,
        use_default_excludes=True,
        max_items=100,
        write_plan=False,
        plan_path=None,
        overwrite_plan=False,
        clock=clock,
        execute=True,
        force=True,
        break_lock=True,
        compress=True,
        compression="zip",
        job_name="Minecraft",
    )

    expected_oz0_root = tmp_path / "testing.OZ0"
    expected_archive = expected_oz0_root / "Minecraft.20260416_163955Z.OZ0.zip"
    expected_manifest = expected_oz0_root / "Minecraft.20260416_163955Z.manifest.json"

    assert result.archive_root == expected_oz0_root
    assert expected_archive.is_file()
    assert expected_manifest.is_file()

    payload = json.loads(expected_manifest.read_text(encoding="utf-8"))
    assert Path(payload["archive_root"]) == expected_oz0_root
    assert payload["archive_format"] == "zip"
    assert payload["compression_method"] == "deflate"
    assert payload["compression_level"] is None
    assert payload["archive_writer_version"] is None
    assert payload["archive_extension"] == ".zip"
    assert payload["archive"]["relative_path"] == expected_archive.name


def test_backup_manifest_persists_gui_job_identity(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    data_root = tmp_path / "data_root"

    files = [
        _FileSpec(relative_path=Path("alpha.txt"), content=b"alpha\n"),
    ]

    _write_source_tree(source_root, files)

    run_backup(
        profile_name="end_to_end",
        source=source_root,
        dry_run=False,
        data_root=data_root,
        excluded_directory_names=None,
        excluded_file_names=None,
        use_default_excludes=True,
        max_items=100,
        write_plan=False,
        plan_path=None,
        overwrite_plan=False,
        clock=None,
        execute=True,
        force=True,
        break_lock=True,
        job_id="job-a-id",
        job_name="Job A",
    )

    manifest_path = _find_single_backup_manifest(source_root.parent / "source.OZ0")
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))

    assert payload["job_id"] == "job-a-id"
    assert payload["job_name"] == "Job A"


def test_restore_accepts_manifest_from_legacy_oz0_layout(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    data_root = tmp_path / "data_root"
    restore_destination = tmp_path / "restore_destination"

    files = [
        _FileSpec(relative_path=Path("alpha.txt"), content=b"alpha\n"),
        _FileSpec(relative_path=Path("nested") / "beta.bin", content=b"\x00\x01\x02\x03"),
    ]

    _write_source_tree(source_root, files)

    run_backup(
        profile_name="end_to_end",
        source=source_root,
        dry_run=False,
        data_root=data_root,
        excluded_directory_names=None,
        excluded_file_names=None,
        use_default_excludes=True,
        max_items=100,
        write_plan=False,
        plan_path=None,
        overwrite_plan=False,
        clock=None,
        execute=True,
        force=True,
        break_lock=True,
    )

    primary_root = source_root.parent / "source.OZ0"
    primary_manifest_path = _find_single_backup_manifest(primary_root)
    legacy_run_root = source_root.parent / "OZ0" / primary_manifest_path.parent.name
    shutil.copytree(primary_manifest_path.parent, legacy_run_root)

    legacy_manifest_path = legacy_run_root / "manifest.json"
    legacy_payload = json.loads(legacy_manifest_path.read_text(encoding="utf-8"))
    legacy_payload["archive_root"] = str(legacy_run_root)
    legacy_manifest_path.write_text(json.dumps(legacy_payload), encoding="utf-8")

    shutil.rmtree(primary_root)

    run_restore(
        manifest_path=legacy_manifest_path,
        destination_root=restore_destination,
        mode="overwrite",
        verify="size",
        dry_run=False,
        data_root=data_root,
        clock=None,
    )

    _assert_tree_matches(source_root, restore_destination, files)


def test_restore_artifacts_do_not_remain_in_live_root_and_are_not_reingested_by_backup(
    tmp_path: Path,
) -> None:
    source_root = tmp_path / "source"
    restored_root = tmp_path / "restored_world"
    data_root = tmp_path / "data_root"

    files = [
        _FileSpec(relative_path=Path("alpha.txt"), content=b"alpha\n"),
        _FileSpec(relative_path=Path("nested") / "beta.bin", content=b"\x00\x01\x02\x03"),
    ]
    _write_source_tree(source_root, files)

    first_clock = FixedClock(datetime.fromisoformat("2026-01-01T00:00:00+00:00"))
    run_backup(
        profile_name="end_to_end",
        source=source_root,
        dry_run=False,
        data_root=data_root,
        excluded_directory_names=None,
        excluded_file_names=None,
        use_default_excludes=True,
        max_items=100,
        write_plan=False,
        plan_path=None,
        overwrite_plan=False,
        clock=first_clock,
        execute=True,
        force=True,
        break_lock=True,
    )

    first_manifest = _find_single_backup_manifest(source_root.parent / "source.OZ0")

    run_restore(
        manifest_path=first_manifest,
        destination_root=restored_root,
        mode="overwrite",
        verify="size",
        dry_run=False,
        data_root=data_root,
        clock=None,
    )

    assert not (restored_root / ".wcbt_restore").exists()
    runtime_artifacts_root = _runtime_artifacts_root(restored_root, "20260101_000000Z")
    assert runtime_artifacts_root.exists()
    assert (runtime_artifacts_root / "restore_summary.json").is_file()

    residue_root = restored_root / ".wcbt_restore" / "restore-run"
    residue_root.mkdir(parents=True, exist_ok=True)
    (residue_root / "restore_summary.json").write_text("transient", encoding="utf-8")

    second_clock = FixedClock(datetime.fromisoformat("2026-01-02T00:00:00+00:00"))
    run_backup(
        profile_name="end_to_end",
        source=restored_root,
        dry_run=False,
        data_root=data_root,
        excluded_directory_names=None,
        excluded_file_names=None,
        use_default_excludes=True,
        max_items=100,
        write_plan=False,
        plan_path=None,
        overwrite_plan=False,
        clock=second_clock,
        execute=True,
        force=True,
        break_lock=True,
    )

    second_manifest = _find_single_backup_manifest(restored_root.parent / "restored_world.OZ0")
    payload = json.loads(second_manifest.read_text(encoding="utf-8"))
    normalized_operation_paths = {
        str(Path(operation["relative_path"]).as_posix()) for operation in payload["operations"]
    }

    assert "alpha.txt" in normalized_operation_paths
    assert "nested/beta.bin" in normalized_operation_paths
    assert all(".wcbt_restore" not in path for path in normalized_operation_paths)


def test_standard_backup_manifest_defaults_backup_origin_to_normal(tmp_path: Path) -> None:
    source_root = tmp_path / "source"
    data_root = tmp_path / "data_root"

    _write_source_tree(
        source_root,
        [_FileSpec(relative_path=Path("alpha.txt"), content=b"alpha\n")],
    )

    run_backup(
        profile_name="end_to_end",
        source=source_root,
        dry_run=False,
        data_root=data_root,
        excluded_directory_names=None,
        excluded_file_names=None,
        use_default_excludes=True,
        max_items=100,
        write_plan=False,
        plan_path=None,
        overwrite_plan=False,
        clock=None,
        execute=True,
        force=True,
        break_lock=True,
    )

    manifest_path = _find_single_backup_manifest(source_root.parent / "source.OZ0")
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))

    assert payload["backup_origin"] == "normal"
    assert payload["archive_format"] is None
    assert payload["compression_method"] is None
    assert payload["compression_level"] is None
    assert payload["archive_writer_version"] is None
    assert payload["archive_extension"] is None
